mod s1200_minimum_absolute_difference;
mod s1266_minimum_time_visiting_all_points;
mod s1984_minimum_difference_between_highest_and_lowest_of_k_scores;
mod s3314_construct_the_minimum_bitwise_array_i;
mod s3507_minimum_pair_removal_to_sort_array_i;
mod s66_plus_one;
mod s744_find_smallest_letter_greater_than_target;
mod s961_n_repeated_element_in_size_2n_array;
