mod s1009_complement_of_base_10_integer;
mod s1582_special_positions_in_a_binary_matrix;
mod s1758_minimum_changes_to_make_alternating_binary_string;
mod s1784_check_if_binary_string_has_at_most_one_segment_of_ones;
mod s3643_flip_square_submatrix_vertically;
